### ISSUE TITLE
Naming convention for new links 

### ISSUE THREAD

**Issue by sunnivin** [MetOs-UiO/info_links_etc#7]
I think it is awesome to see the contributions from @sarambl and @franzihe to give pointers to useful code (:partying_face: )! But, I think we should be very precise when we choose the names of the different new features to avoid unnecessary confusion. 

For instance, I think the name of the document containing the links and the link in the README.md should be identical. The name of the link "Other links to code etc" points to the file "info_links_etc/Links_to_useful_code.md". 

Also, I feel that the name "links_to_useful_code" is a little bit too general. Inside this file, we find some links to different set-up configurations and some links to data series. Would it not be better to have a precise name and individual file for the different groups of links?

**Comment by sarambl** [comment]
Cool! I don't understand what you mean by the name og links and links, but if you make a pull request, I will probably understand :D 
on your second point, I completely agree! I think one of us should think about a setup/structure, and then we can revise it together?

**Comment by sarambl** [comment]
Okey, I tried to re organize a bit in a new branch here https://github.com/MetOs-UiO/info_links_etc/tree/re_organize 
Basically, I would try to make a easy structure where the folders make natural nesting. Each folder has a readme which should redirect to the content. 
Have a look and see what you think @sunnivin ?

**Comment by sarambl** [comment]
Also, I wondered why you add the links with the full adress?? I.e. - [Dotfiles and editors](https://github.com/MetOs-UiO/info_links_etc/blob/main/computer_configuration/dotfiles_and_editors.md) instead of [Dotfiles and editors](computer_configuration/dotfiles_and_editors.md) (which works in the github and doesn't point to particular branch.

**Comment by sunnivin** [comment]
> Also, I wondered why you add the links with the full adress?? I.e. - [Dotfiles and editors] (https://github.com/MetOs-UiO/info_links_etc/blob/main/computer_configuration/dotfiles_and_editors.md) instead of [Dotfiles and editors] (computer_configuration/dotfiles_and_editors.md) (which works in the github and doesn't point to particular branch.

I agree that it seems better to have a local link for the pages. Thank you for pointing this out.

**Comment by sunnivin** [comment]
Thank you for the suggestions for a more systematic organization of the names.
